# Generated by Django 3.0.3 on 2020-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveinfo',
            name='People',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
