# Generated by Django 3.0.3 on 2020-09-15 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_reserveinfo_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveinfo',
            name='When',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
