# Generated by Django 3.0.3 on 2020-09-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_reserveinfo_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveinfo',
            name='When',
        ),
    ]
