# Generated by Django 3.0.3 on 2020-09-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_reserveinfo_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveinfo',
            name='Timing',
        ),
    ]
